"""
CONSTANTS
"""

PUNCTUATION = " ,.!?1234567890()#@$%&*"

ALPHABET_LOWER = "abcdefghijklmnopqrstuvwxyz"
ALPHABET_UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

ALPHABET_LOWER_REVERSE = ALPHABET_LOWER[::-1]
ALPHABET_UPPER_REVERSE = ALPHABET_UPPER[::-1]

"""
END OF CONSTANTS
"""
